# Generated by Django 5.2.1 on 2025-08-24 19:26

import api.menu.menu_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.menu.menu_models.custom_filename),
        ),
    ]
