# Generated by Django 5.2.1 on 2025-08-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
