# Generated by Django 5.2.1 on 2025-08-29 06:45

import api.menu.menu_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=api.menu.menu_models.get_next_display_order_available, unique=True),
        ),
    ]
