# Generated by Django 5.2.1 on 2025-08-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order']},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='order',
            new_name='display_order',
        ),
    ]
