# Generated by Django 5.2.1 on 2025-09-01 10:49

import api.menu.menu_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=api.menu.menu_models.get_next_display_order_available),
        ),
    ]
